SERVE_MEDIA = True

# PINAX_THEME=''
CONTACT_EMAIL='chipy@chipy.org'
URCHIN_ID='UA-2413988'
BBAUTH_APP_ID='LGtYvH7IkY1hd8M7PQEahc7hXq6AvlVkz5c-'
BBAUTH_SHARED_SECRET='a5e3f94759292fbab5ecb4f7bb86a7cc'
SITE_NAME='ChiPy'
# MAILER_PAUSE_SEND=''
# SERVE_MEDIA=''
# ACCOUNT_OPEN_SIGNUP=''
# ACCOUNT_REQUIRED_EMAIL=''
# ACCOUNT_EMAIL_VERIFICATION=''
EMAIL_CONFIRMATION_DAYS='15'
# LOGIN_REDIRECT_URLNAME=''
DEFAULT_FROM_EMAIL="chipy@chipy.org"

